### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by KristjanESPERANTO** [tabsl/MMM-MySQLData#1]
Thanks for this nice module! You wrote MIT in the package.json but it would be nice when you also add a LICENSE file to your repository.

**Comment by tabsl** [comment]
done ;-) https://github.com/tabsl/MMM-MySQLData/commit/29721d2e722b7fde379dfa43f9009ab0ca4281db

**Comment by KristjanESPERANTO** [comment]
Nice :+1:

By the way, your module is also displayed in [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I'm working on. Feel free to give me feedback if you have any ideas to improve the presentation.
